// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedFj3Xxri__goysd4V4ySiqftPk3H33k',
    appId: '1:523114257681:android:b8c823a79404c537c680b0',
    messagingSenderId: '523114257681',
    projectId: 'drawhub-bacb2',
    storageBucket: 'drawhub-bacb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBD5hCCdqObkwA3dS4KI_T3A6O_6Huo2A',
    appId: '1:523114257681:ios:16435e9b43dccc4dc680b0',
    messagingSenderId: '523114257681',
    projectId: 'drawhub-bacb2',
    storageBucket: 'drawhub-bacb2.firebasestorage.app',
    iosBundleId: 'com.example.drawHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBD5hCCdqObkwA3dS4KI_T3A6O_6Huo2A',
    appId: '1:523114257681:ios:16435e9b43dccc4dc680b0',
    messagingSenderId: '523114257681',
    projectId: 'drawhub-bacb2',
    storageBucket: 'drawhub-bacb2.firebasestorage.app',
    iosBundleId: 'com.example.drawHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ_J3aFoTzGoGbuDeQxpXzcMIMdMV0KYo',
    appId: '1:523114257681:web:f6ff2577e3a1deb3c680b0',
    messagingSenderId: '523114257681',
    projectId: 'drawhub-bacb2',
    authDomain: 'drawhub-bacb2.firebaseapp.com',
    storageBucket: 'drawhub-bacb2.firebasestorage.app',
  );
}
